### ISSUE TITLE
Doesnt work on Chrome > Android 9 Pie 

### ISSUE THREAD

**Issue by fedehiga** [lukemnet/tridi#175]
Hi! I'm just testing your script on my xiaomi mi a1 phone (Android 9 Pie and Chrome) and it seems it doesn't work at all when i drag over the examples. It only works when i tap the buttons @ the example with custom controls.

On desktop it works very well.

**Comment by lwojcik** [comment]
Hi! Thanks for the heads-up. I'll have a look at it.

**Comment by aelsharawi** [comment]
any fix for that?

**Comment by lwojcik** [comment]
Hi! Thanks for reporting the issue. I sincerely apologize for a late reply. My priorities around open source have been all around the place these days.

Until recently I've had no device running anything Android newer than 6 and I had a bit of hard time reproducing and properly diagnosing the issue. A year later I have a few devices running recent Android versions at my disposal and I'll try to provide a fix within next few weeks.

**Comment by lwojcik** [comment]
I sincerely apologize it took so long to fix this and I appreciate everyone who reached out about this issue. The project should now work correctly on mobile devices. The API didn't change but you may want to check your `dragInterval` and / or `touchDragInterval` options and re-adjust them to your taste - the issue was directly connected to them.

NPM release will arrive later.
