### ISSUE TITLE
Es6 import error, is not a module

### ISSUE THREAD

**Issue by sfrinx** [lukemnet/tridi#238]
I try to include the plugin on this way on an ionic (angular 8) app:

`import * as Tridi from "tridi";`

But i got this error: 

`File /node_modules/tridi/dist/js/tridi.min.d.ts' is not a module.`

How can i fix this error?

**Comment by lwojcik** [comment]
Hi! Thanks for reporting the issue.

ES6 module support is non-existent due to the fact it's build from TS source as `"module": "none"` set in `tsconfig.json` and there's no bundler to handle that automatically. Rebuilding the library as `"module": "es6"` should theoretically fix the issue.

I'll have a proper look and try to release an update with a fix next week.

**Comment by lwojcik** [comment]
I solved the issue by integrating Webpack into a build process to export Tridi as UMD library. However, I had a bit of hard time forcing Webpack to export a TypeScript class constructor without breaking backwards compatibility, so I decided to publish the fix as a [new major update](https://github.com/lukemnet/tridi/releases/tag/v2.0.0) that exports a factory method instead of a class. Other than that, whole API layer remains unchanged.

I'm also aware of the fact it's not overly straighforward to integrate Tridi with web applications / SPAs and I'm exploring ways of alleviating that pain, most likely by offering wrapper components for popular frameworks, with React and Vue.js being most likely to come first. Angular might take more time as I have little experience with it, but I'm not excluding it yet.
